2023-08-17 01:26:54,520 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpage/default.html'), <traceback object at 0x000002104C8E5FC0>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html
2023-08-17 01:26:54,703 ERROR "GET /news/ HTTP/1.1" 500 145 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 01:29:20,216 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpage/default.html'), <traceback object at 0x000002104DD6F100>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html
2023-08-17 01:29:20,257 ERROR "GET /news/ HTTP/1.1" 500 145 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 01:32:06,760 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpage/default.html'), <traceback object at 0x0000020293C244C0>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html
2023-08-17 01:32:06,817 ERROR "GET /news/ HTTP/1.1" 500 145 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 01:33:15,554 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpage/default.html'), <traceback object at 0x000001659501B0C0>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html
2023-08-17 01:33:15,648 ERROR "GET /news/ HTTP/1.1" 500 145 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 01:36:11,431 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpage/default.html'), <traceback object at 0x00000222D735D580>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html
2023-08-17 01:36:11,513 ERROR "GET /news/ HTTP/1.1" 500 146935 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 01:51:22,397 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpage/default.html'), <traceback object at 0x0000022B9A198C00>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html
2023-08-17 01:51:22,412 ERROR "GET /news/ HTTP/1.1" 500 146959 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 01:53:08,906 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpage/default.html'), <traceback object at 0x000001766B0110C0>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpage/default.html
2023-08-17 01:53:08,922 ERROR "GET /news/ HTTP/1.1" 500 146959 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 01:58:33,398 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpagess/default.html'), <traceback object at 0x0000026171D38B00>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html
2023-08-17 01:58:33,410 ERROR "GET /news/ HTTP/1.1" 500 146890 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 21:33:09,450 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpagess/default.html'), <traceback object at 0x000001A8EE952140>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html
2023-08-17 21:33:09,466 ERROR "GET /news/ HTTP/1.1" 500 147164 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 21:33:10,863 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpagess/default.html'), <traceback object at 0x000001A8EE5EF580>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html
2023-08-17 21:33:10,874 ERROR "GET /news/ HTTP/1.1" 500 146890 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 21:33:34,697 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpagess/default.html'), <traceback object at 0x000001A8EE7C02C0>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html
2023-08-17 21:33:34,710 ERROR "GET /news/ HTTP/1.1" 500 147027 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 21:44:46,684 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpagess/default.html'), <traceback object at 0x0000019F23519440>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html
2023-08-17 21:44:46,690 ERROR "GET /news/ HTTP/1.1" 500 147578 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 21:47:16,454 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpagess/default.html'), <traceback object at 0x000001B467F79400>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html
2023-08-17 21:47:16,469 ERROR "GET /news/ HTTP/1.1" 500 147597 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 21:47:16,814 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpagess/default.html'), <traceback object at 0x000001B469234E80>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html
2023-08-17 21:47:16,826 ERROR "GET /news/ HTTP/1.1" 500 147323 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-08-17 21:49:49,827 ERROR Internal Server Error: /news/ C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpagess/default.html'), <traceback object at 0x000001F7DBE399C0>)
Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpagess/default.html
2023-08-17 21:49:49,835 ERROR "GET /news/ HTTP/1.1" 500 147578 C:\Users\User1\Documents\PWS\Модули D\Django\D2\newspaperproject\venv\Lib\site-packages\django\core\servers\basehttp.py None
